apiVersion: apps/v1
kind: Deployment
metadata:  ### metadata del deploment
  name: deployment-test
  annotations:
    kubernetes.io/change-cause: "node port 30080"
  labels:
    app: front
spec:   ### inicia info del replicaSet
  replicas: 5
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec: ### inicia info del contenedor
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 80  # container port
      nodePort: 30080
