---
apiVersion: v1
kind: Namespace
metadata: 
  name: qa
  labels:
    name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
  namespace: qa
spec:
  hard: 
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:  ### metadata del deploment
  name: deployment-test
  namespace: qa
  labels:
    app: front
spec:   ### inicia info del replicaSet
  replicas: 5
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec: ### inicia info del contenedor
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 150
