apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: apps/v1
kind: Deployment
metadata:  ### metadata del deploment
  name: deployment-test
  labels:
    app: mysql
spec:   ### inicia info del replicaSet
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: ### inicia info del contenedor
      containers:
      - name: mysql
        image: mysql:5.7
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: "123456789"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: vol-mysql
      volumes:
        - name: vol-mysql
          persistentVolumeClaim:
          claimName: test-pvc
